/****************************************************************************
*   Generated by ACUITY 6.0.14
*
*   Neural Network application project entry file
****************************************************************************/
/*-------------------------------------------
                Includes
-------------------------------------------*/
#if defined(ENABLE_DTLN) && !defined(ENABLE_NS_NN)
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include "pocketfft_hdronly.h"
#include "AudioFile.h"
#include "AudioCore.h"
#include <utils/util.h>
#include <utils/circlebuf.h>

#define _BASETSD_H

#include "DTLN_defs.h"

using namespace std;

typedef complex<float> cpx_type;

#define _BASETSD_H

#define BILLION                                 1000000000
static unsigned long long get_perf_count()
{
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (unsigned long long)((unsigned long long)ts.tv_nsec + (unsigned long long)ts.tv_sec * BILLION);
}

void ExportWAV(
        const std::string & Filename,
		const std::vector<float>& Data,
		unsigned SampleRate) {
    AudioFile<float>::AudioBuffer Buffer;
	Buffer.resize(1);

	Buffer[0] = Data;
	size_t BufSz = Data.size();

	AudioFile<float> File;
	File.setAudioBuffer(Buffer);
	File.setAudioBufferSize(1, (int)BufSz);
	File.setNumSamplesPerChannel((int)BufSz);
	File.setNumChannels(1);
	File.setBitDepth(16);
	File.setSampleRate(SAMEPLERATE);
	File.save(Filename, AudioFileFormat::Wave);
}

void __calc_mag_phase(vector<cpx_type> fft_res, float* in_mag, float* in_phase, int count)
{
    for (int i = 0; i < count; i++)
	{
        in_mag[i] = sqrtf(fft_res[i].real() * fft_res[i].real() + fft_res[i].imag() * fft_res[i].imag());
        in_phase[i] = atan2f(fft_res[i].imag(), fft_res[i].real());
    }
}

void tflite_create(trg_engine* engine)
{
    //---------------------------------------------
    engine->model1 = TfLiteModelCreateFromFile(DTLN_MODEL_A);
    if (engine->model1 == NULL)
    {
        printf("load model1 fail\n");
        return;
    }

    // Build the interpreter
    TfLiteInterpreterOptions* options = TfLiteInterpreterOptionsCreate();
    TfLiteInterpreterOptionsSetNumThreads(options, 1);

    // Create the interpreter.
    engine->interpreter_1 = TfLiteInterpreterCreate(engine->model1, options);
    if (engine->interpreter_1 == nullptr) {
        printf("Failed to create interpreter");
        return;
    }

    // Allocate tensor buffers.
    if (TfLiteInterpreterAllocateTensors(engine->interpreter_1) != kTfLiteOk) {
        printf("Failed to allocate tensors!");
        return;
    }

    //---------------------------------------------
    engine->model2 = TfLiteModelCreateFromFile(DTLN_MODEL_B);
    if (engine->model2 == NULL)
    {
        printf("load model2 fail\n");
        return;
    }

    // Create the interpreter.
    engine->interpreter_2 = TfLiteInterpreterCreate(engine->model2, options);
    if (engine->interpreter_2 == nullptr) {
        printf("Failed to create interpreter");
        return;
    }

    // Allocate tensor buffers.
    if (TfLiteInterpreterAllocateTensors(engine->interpreter_2) != kTfLiteOk) {
        printf("Failed to allocate tensors!");
        return;
    }

    ////////////////////////////////////

    engine->input_details_1[0] = TfLiteInterpreterGetInputTensor(engine->interpreter_1, 0);
    engine->input_details_1[1] = TfLiteInterpreterGetInputTensor(engine->interpreter_1, 1);
	engine->input_details_1[2] = TfLiteInterpreterGetInputTensor(engine->interpreter_1, 2);
    engine->output_details_1[0] = TfLiteInterpreterGetOutputTensor(engine->interpreter_1, 0);
    engine->output_details_1[1] = TfLiteInterpreterGetOutputTensor(engine->interpreter_1, 1);

    engine->input_details_2[0] = TfLiteInterpreterGetInputTensor(engine->interpreter_2, 0);
    engine->input_details_2[1] = TfLiteInterpreterGetInputTensor(engine->interpreter_2, 1);
	engine->input_details_2[2] = TfLiteInterpreterGetInputTensor(engine->interpreter_2, 2);
    engine->output_details_2[0] = TfLiteInterpreterGetOutputTensor(engine->interpreter_2, 0);
    engine->output_details_2[1] = TfLiteInterpreterGetOutputTensor(engine->interpreter_2, 1);
	printf("tflite_create ok\n");
}

void tflite_destroy(trg_engine* engine)
{
    TfLiteModelDelete(engine->model1);
    TfLiteModelDelete(engine->model2);
}


void tflite_infer(trg_engine* m_pEngine)
{
    int i;
	float mic_mag[FFT_OUT_SIZE] ={0}; ;
    float mic_phase[FFT_OUT_SIZE] = { 0 };
    float lpb_mag[FFT_OUT_SIZE]={0};
    float lpb_phase[FFT_OUT_SIZE]={0};

	float estimated_block[DTLN_BLOCK_LEN] ={0};

    float fft_mic[DTLN_BLOCK_LEN];
    std::vector<cpx_type> fft_res(DTLN_BLOCK_LEN);
    float lpb_in[DTLN_BLOCK_LEN];
    std::vector<cpx_type> lpb_res(DTLN_BLOCK_LEN);

    std::vector<size_t> shape;
    shape.push_back(DTLN_BLOCK_LEN);
    std::vector<size_t> axes;
    axes.push_back(0);
    std::vector<ptrdiff_t> stridel, strideo;
    strideo.push_back(sizeof(cpx_type));
    stridel.push_back(sizeof(float));
    for (i = 0; i < DTLN_BLOCK_LEN; i++){
        fft_mic[i] = m_pEngine->mic_buffer[i];
		lpb_in[i]= m_pEngine->lpb_buffer[i];
	}

    //apply FFT to input wav data
    pocketfft::r2c(shape, stridel, strideo, axes, pocketfft::FORWARD, fft_mic, fft_res.data(), (float)1.0);
	__calc_mag_phase(fft_res, mic_mag, mic_phase, FFT_OUT_SIZE);
    pocketfft::r2c(shape, stridel, strideo, axes, pocketfft::FORWARD, lpb_in,lpb_res.data(), (float)1.0);
	__calc_mag_phase(lpb_res, lpb_mag, lpb_phase, FFT_OUT_SIZE);

    memcpy(m_pEngine->input_details_1[0]->data.f, mic_mag, FFT_OUT_SIZE * sizeof(float));
	memcpy(m_pEngine->input_details_1[1]->data.f, lpb_mag, FFT_OUT_SIZE * sizeof(float));
    memcpy(m_pEngine->input_details_1[2]->data.f, m_pEngine->states_a, DTLN_STATE_SIZE * sizeof(float));

    if (TfLiteInterpreterInvoke(m_pEngine->interpreter_1) != kTfLiteOk) {
        printf("Error invoking detection model");
    }

    float* out_mask = m_pEngine->output_details_1[0]->data.f;
    memcpy(m_pEngine->states_a, m_pEngine->output_details_1[1]->data.f, DTLN_STATE_SIZE * sizeof(float));
	for (i = 0; i < FFT_OUT_SIZE; i++) {
        fft_res[i] = cpx_type(mic_mag[i] * out_mask[i] * cosf(mic_phase[i]),
						mic_mag[i] * out_mask[i] * sinf(mic_phase[i]));
	}

    pocketfft::c2r(shape, strideo, stridel, axes, pocketfft::BACKWARD, fft_res.data(), fft_mic, (float)1.0);

    for (i = 0; i < DTLN_BLOCK_LEN; i++)
        estimated_block[i] = fft_mic[i] / DTLN_BLOCK_LEN;

    memcpy(m_pEngine->input_details_2[0]->data.f, estimated_block, DTLN_BLOCK_LEN * sizeof(float));
	memcpy(m_pEngine->input_details_2[1]->data.f, m_pEngine->lpb_buffer, DTLN_BLOCK_LEN * sizeof(float));
    memcpy(m_pEngine->input_details_2[2]->data.f, m_pEngine->states_b, DTLN_STATE_SIZE * sizeof(float));
    if (TfLiteInterpreterInvoke(m_pEngine->interpreter_2) != kTfLiteOk) {
        printf("Error invoking detection model");
    }

    float* out_block = m_pEngine->output_details_2[0]->data.f;
    memcpy(m_pEngine->states_b, m_pEngine->output_details_2[1]->data.f, DTLN_STATE_SIZE * sizeof(float));

    //apply overlap_add
    memmove(m_pEngine->out_buffer, m_pEngine->out_buffer + DTLN_BLOCK_SHIFT, (DTLN_BLOCK_LEN - DTLN_BLOCK_SHIFT) * sizeof(float));
    memset(m_pEngine->out_buffer + (DTLN_BLOCK_LEN - DTLN_BLOCK_SHIFT), 0, DTLN_BLOCK_SHIFT * sizeof(float));
    for (i = 0; i < DTLN_BLOCK_LEN; i++)
        m_pEngine->out_buffer[i] += out_block[i];
}

#ifdef __cplusplus
extern "C" {
#endif
/*-------------------------------------------
                  Main Functions
-------------------------------------------*/


int mymain22(int argc,char **argv)
{
    if(argc != 4)
    {
        printf("usage: %s <micfile> <lpbfile> <outputfile>\n",argv[0]);
        return 0;
    }

    trg_engine eng1;
    tflite_create(&eng1);

    std::vector<float>  testaecdata; //vector used to store enhanced data in a wav file
    AudioFile<float> inputmicfile;
    AudioFile<float> inputlpbfile;
    std::string micfile=argv[1];
    std::string lpbfile=argv[2];
    inputmicfile.load(micfile);
    inputlpbfile.load(lpbfile);
    int audiolen=inputmicfile.getNumSamplesPerChannel();
    int process_num=(audiolen-DTLN_BLOCK_LEN)/DTLN_BLOCK_SHIFT;

    printf("process_num=%d\n",process_num);
    for(int i=0;i<process_num;i++)
    {
        printf("process:%d\n",i);
        unsigned long long sigStart = get_perf_count();

        memmove(eng1.mic_buffer, eng1.mic_buffer + DTLN_BLOCK_SHIFT, (DTLN_BLOCK_LEN - DTLN_BLOCK_SHIFT) * sizeof(float));
        memmove(eng1.lpb_buffer, eng1.lpb_buffer + DTLN_BLOCK_SHIFT, (DTLN_BLOCK_LEN - DTLN_BLOCK_SHIFT) * sizeof(float));

        for(int n=0;n<DTLN_BLOCK_SHIFT;n++){
            eng1.mic_buffer[n+DTLN_BLOCK_LEN-DTLN_BLOCK_SHIFT] = inputmicfile.samples[0][n+i*DTLN_BLOCK_SHIFT];
            eng1.lpb_buffer[n+DTLN_BLOCK_LEN-DTLN_BLOCK_SHIFT] = inputlpbfile.samples[0][n+i*DTLN_BLOCK_SHIFT];
        }

        tflite_infer(&eng1);

        unsigned long long sigEnd = get_perf_count();
        float msVal = (float)(sigEnd - sigStart)/1000000;
        printf("Run: %.2fms\n",msVal);

        for(int j=0;j<DTLN_BLOCK_SHIFT;j++){
            testaecdata.push_back(eng1.out_buffer[j]);    //for one forward process save first BLOCK_SHIFT model output samples
        }
    }
    printf("process end.save out\n");

    ExportWAV(argv[3],testaecdata,SAMEPLERATE);

    return 0;
}

// 简易short转浮点
static inline void short_to_float(const int16_t *input, float *output, size_t num_samples)
{
	for (size_t i = 0; i < num_samples; ++i)
	{
		output[i] = input[i] / 32768.0f;  // 将短整型值转换为浮点型 (范围: -1.0 到 1.0)
	}
}

// 简易浮点转short
static inline void float_to_short(const float *input, int16_t *output, size_t num_samples)
{
	for (size_t i = 0; i < num_samples; ++i)
	{
		// 确保浮点值在有效范围内
		if (input[i] < -1.0f)
		{
			output[i] = -32768;  // 下限
		}
		else if (input[i] > 1.0f)
		{
			output[i] = 32767;   // 上限
		}
		else
		{
			// 将浮点值映射到短整型范围
			output[i] = (int16_t)(input[i] * 32767);  // 转换
		}
	}
}

static trg_engine *g_peng = NULL;

void *dtln_create_handle(void)
{
    if(g_peng)
    {
        return (void*)g_peng;
    }
    g_peng = new trg_engine;
    tflite_create(g_peng);

    return (void*)g_peng;
}

int dtln_destroy_handle(void*phandle)
{
    if(g_peng)
    {
        return 0;
    }
    trg_engine *peng = (trg_engine*)phandle;

    delete peng;
    return 0;
}

int dtln_train_by_handle(void*phandle, short *pindata, short *pplbdata, int indatasize, short *poutdata)
{
    int retlen = 0;
    trg_engine *peng = (trg_engine*)phandle;

    if(peng)
    {
        memmove(peng->mic_buffer, peng->mic_buffer + DTLN_BLOCK_SHIFT, (DTLN_BLOCK_LEN - DTLN_BLOCK_SHIFT) * sizeof(float));
        memmove(peng->lpb_buffer, peng->lpb_buffer + DTLN_BLOCK_SHIFT, (DTLN_BLOCK_LEN - DTLN_BLOCK_SHIFT) * sizeof(float));

        short_to_float((short*)pindata, peng->mic_buffer+DTLN_BLOCK_SHIFT, indatasize/2);
        if(pplbdata)
        {
            short_to_float((short*)pplbdata, peng->lpb_buffer+DTLN_BLOCK_SHIFT, indatasize/2);
        }
        else
            memset(peng->lpb_buffer, 0, 512*sizeof(float));

        tflite_infer(peng);

        float_to_short(peng->out_buffer, (short*)poutdata, indatasize/2);

        retlen = indatasize;
    }
    else
    {
        memcpy(poutdata, pindata, indatasize);
    }
    return retlen;
}


static FILE *pfd_ao = NULL;

static FILE *pfd_ai = NULL;
static FILE *pfd_lpb = NULL;
static FILE *pfd_dtln = NULL;

static struct circlebuf ai_packet;
static pthread_mutex_t ai_mutex;

static struct circlebuf lpb_packet;
static pthread_mutex_t lpb_mutex;

static int AudioOutCb(char *DataBuffer, int DataSize, void *pContext)
{
    //printf("AudioOutCb DataSize:%d\n", DataSize);
    if(pfd_ao)
    {
        if(fread(DataBuffer, 1, DataSize, pfd_ao) != (size_t)DataSize)
        {
            //printf("AudioInCbFunc read fail\n");
            fseek(pfd_ao, 0, SEEK_SET);
        }

        pthread_mutex_lock(&lpb_mutex);
        circlebuf_push_back(&lpb_packet, DataBuffer, DataSize);
        pthread_mutex_unlock(&lpb_mutex);
    }

    return DataSize;
}

static int AudioInCb(char *DataBuffer, int DataSize, void *pContext)
{
    trg_engine *peng = (trg_engine*)pContext;
    if(peng)
    {
        if(pfd_ai)
            fwrite(DataBuffer, 1, DataSize, pfd_ai);

        // memmove(peng->mic_buffer, peng->mic_buffer + DTLN_BLOCK_SHIFT, (DTLN_BLOCK_LEN - DTLN_BLOCK_SHIFT) * sizeof(float));
        // memmove(peng->lpb_buffer, peng->lpb_buffer + DTLN_BLOCK_SHIFT, (DTLN_BLOCK_LEN - DTLN_BLOCK_SHIFT) * sizeof(float));

        // short_to_float((short*)DataBuffer, peng->mic_buffer+DTLN_BLOCK_SHIFT, DataSize/2);
        // memset(peng->lpb_buffer, 0, 512*sizeof(float));

        // tflite_infer(peng);

        // float_to_short(peng->out_buffer, (short*)DataBuffer, DataSize/2);
        char tmpbuf[1024] = {0};
#if 0
        dtln_train_by_handle(pContext, (short*)DataBuffer, NULL, DataSize, (short*)tmpbuf);
        if(pfd_dtln)
            fwrite(tmpbuf, 1, DataSize, pfd_dtln);
#else
        char tmplpbbuf[1024]={0};
        char tmpoutbuf[1024]={0};
        circlebuf_push_back(&ai_packet, DataBuffer, DataSize);
        #define DTLN_NEED_LEN    512
        while (ai_packet.size >= DTLN_NEED_LEN)
        {
            circlebuf_pop_front(&ai_packet, tmpbuf, DTLN_NEED_LEN);

            pthread_mutex_lock(&lpb_mutex);
            if(lpb_packet.size >= DTLN_NEED_LEN)
            {
                memset(tmplpbbuf, 0, sizeof(tmplpbbuf));
                circlebuf_pop_front(&lpb_packet, tmplpbbuf, DTLN_NEED_LEN);
            }
            pthread_mutex_unlock(&lpb_mutex);

            dtln_train_by_handle(pContext, (short *)tmpbuf, (short *)tmplpbbuf, DTLN_NEED_LEN, (short *)tmpoutbuf);
            //circlebuf_push_back(&pmgnt_audio->record_packet, tmpoutbuf, DTLN_NEED_LEN);
            if(pfd_dtln)
            {
                fwrite(tmpoutbuf, 1, DTLN_NEED_LEN, pfd_dtln);
            }
            if(pfd_lpb)
            {
                fwrite(tmplpbbuf, 1, DTLN_NEED_LEN, pfd_lpb);
            }
        }
#endif
    }
    return DataSize;
}

int mymain(int argc,char **argv)
{
    // if(argc != 4)
    // {
    //     printf("usage: %s <micfile> <lpbfile> <outputfile>\n",argv[0]);
    //     return 0;
    // }

    // trg_engine *peng1 = new trg_engine;
    // tflite_create(peng1);

    void *pdtln_handle = dtln_create_handle();
#ifndef NDEBUG
    if(!pfd_ai)
        pfd_ai = fopen("ai.pcm", "wb");
    if(!pfd_lpb)
        pfd_lpb = fopen("lpb.pcm", "wb");
    if(!pfd_dtln)
        pfd_dtln = fopen("dtln.pcm", "wb");
    if(!pfd_ao)
        pfd_ao = fopen("ao.pcm", "rb");
#endif//#ifdef NDEBUG
    int ai_stream_id = 0;
    int ao_stream_id = 0;
    int Channels = 1;
	int SampleBits = 16;
	int SampleRate = 16000;
	int Blocks = 4;
	//int BlockTime = 40;
	int SamplesPerBlock = DTLN_BLOCK_SHIFT;//SampleRate * BlockTime / 1000;
	//int BlockSize = SamplesPerBlock * Channels * (SampleBits / 8);

    pthread_mutex_init(&ai_mutex, NULL);
    circlebuf_init(&ai_packet);
    circlebuf_reserve(&ai_packet, 1024);

    pthread_mutex_init(&lpb_mutex, NULL);
    circlebuf_init(&lpb_packet);
    circlebuf_reserve(&lpb_packet, 1024);

    AudioCore_SetRecordVolume(10);
    AudioCore_SetPlayVolume(10);
    // 打开播放设备
    ao_stream_id = Audio_Player_Open();
    Audio_Player_SetDevice(ao_stream_id, "default");
    Audio_Player_SetFormat(ao_stream_id, Channels, SampleBits, SampleRate);
    Audio_Player_SetCache(ao_stream_id, Blocks, SamplesPerBlock);
    Audio_Player_SetMode(ao_stream_id, false, AudioOutCb, NULL);
    Audio_Player_SetVolume(ao_stream_id, 50);
    Audio_Player_Start(ao_stream_id);

    // 打开录音设备
	ai_stream_id = Audio_Recorder_Open();

	// 设置录音参数
	Audio_Recorder_SetDevice(ai_stream_id, "default");
	Audio_Recorder_SetFormat(ai_stream_id, Channels, SampleBits, SampleRate);
	Audio_Recorder_SetCache(ai_stream_id, Blocks, SamplesPerBlock);
	Audio_Recorder_SetMode(ai_stream_id, false, AudioInCb, (void*)pdtln_handle);
	Audio_Recorder_SetVolume(ai_stream_id, 100);
	Audio_Recorder_Start(ai_stream_id);

    unsigned long long lsigEnd = get_perf_count();
    printf("\nplease press twice ENTER to exit this sample, ao_stream_id:%d, ai_stream_id:%d\n", ao_stream_id, ai_stream_id);
	getchar();
    getchar();

    printf("############# exit lost:%lld ###############\n", (get_perf_count() - lsigEnd)/1000000);
    //delete peng1;

    dtln_destroy_handle(pdtln_handle);

    if(ao_stream_id != 0)
    {
        printf("Audio_Player_Stop\n");
        Audio_Player_Stop(ao_stream_id);
		Audio_Player_Close(ao_stream_id);
        ao_stream_id = 0;
    }

	if (ai_stream_id != 0)
	{
        printf("Audio_Recorder_Stop\n");
        Audio_Recorder_Stop(ai_stream_id);
		Audio_Recorder_Close(ai_stream_id);
		ai_stream_id = 0;
	}

    pthread_mutex_destroy(&ai_mutex);
    circlebuf_free(&ai_packet);

    pthread_mutex_destroy(&lpb_mutex);
    circlebuf_free(&lpb_packet);

    if(pfd_ai)
    {
        fclose(pfd_ai);
        pfd_ai = NULL;
    }
    if(pfd_dtln)
    {
        fclose(pfd_dtln);
        pfd_dtln = NULL;
    }
    if(pfd_ao)
    {
        fclose(pfd_ao);
        pfd_ao = NULL;
    }
    if(pfd_lpb)
    {
        fclose(pfd_lpb);
        pfd_lpb = NULL;
    }
    return 0;
}

#ifdef __cplusplus
}
#endif

#endif // _