import { State, I18n } from "shared.slint";
import { NumberOptionPicker } from "NumberOptionPicker.slint";

export component AbsentModeTimePicker inherits NumberOptionPicker {
    selected-value: State.absent-mode-minutes;
    second-unit: false;

    picked(value) => {
        State.absent-mode-minutes = value;
        State.absent-mode-time = I18n.minute_label(value);
        State.save-int-setting("mode.absent_timeout_min", value);
        State.active-overlay = "";
    }
}
