import { I18n } from "shared.slint";

export component ButtonEffectMqEIB inherits Rectangle {
    width: 110px;
    height: 132px;
    clip: true;
    border-radius: 14px;
    background: #d16f29ff;
    Image {
        x: 39px; y: 36px;
        width: 32px;
        height: 32px;
        source: @image-url("../assets/images/9ye3C.png");
        image-fit: contain;
    }
    Rectangle {
        x: 15px; y: 76px;
        width: 80px;
        height: 20px;
        background: #00000000;
        Text {
            height: parent.height;
            width: parent.width;
            text: I18n.text("door_open");
            color: #ffffffff;
            font-family: "Inter";
            font-size: 14px;
            font-weight: 500;
            horizontal-alignment: center;
            vertical-alignment: center;
        }
    }
}
