import { State, I18n, InteractiveSlider } from "shared.slint";
import { ButtonEffectLkIXT } from "ButtonEffectLkIXT.slint";
import { ButtonEffectM9yPz } from "ButtonEffectM9yPz.slint";

export component EVCalling inherits Rectangle {
    width: 1024px;
    height: 600px;
    clip: true;
    background: #030712ff;
    Rectangle {
        x: 0px; y: 0px;
        width: 1024px;
        height: 600px;
        background: @linear-gradient(225.000deg, #101828ff 0%, #1e2939ff 50%, #101828ff 100%);
        clip: true;
        Rectangle {
            x: 0px; y: 0px;
            width: 1024px;
            height: 50px;
            background: #00000000;
            Text {
                x: 26px; y: 11px;
                text: I18n.text("guard_room_call");
                color: #ffffffff;
                font-family: "Inter";
                font-size: 18px;
                font-weight: 500;
            }
            Rectangle {
                x: 964px; y: 7px;
                width: 36px;
                height: 36px;
                background: #36415380;
                border-radius: 14px;
                Image {
                    x: 8px; y: 8px;
                    width: 20px;
                    height: 20px;
                    source: @image-url("../assets/images/6o4cI.png");
                    image-fit: contain;
                }
                TouchArea { width: parent.width; height: parent.height; clicked => { State.play-touch-sound(); State.current-page = "LCvek"; State.pressed-effect = ""; State.call-effect-locked = false; State.ev-call-effect-active = false; State.ev-cancel-effect-active = false; } }
            }
        }
        Rectangle {
            x: 0px; y: 50px;
            width: 1024px;
            height: 420px;
            background: #00000000;
            Rectangle {
                x: 24px; y: 0px;
                width: 850px;
                height: 420px;
                background: #1e2939ff;
                border-radius: 16px;
                clip: true;
                Rectangle {
                    x: 358px; y: 65px;
                    background: #00000000;
                }
                Image {
                    x: 352px; y: 50px;
                    source: State.ev-image;
                    image-fit: contain;
                }
                Text {
                    x: 248px; y: 350px;
                    width: 353px;
                    height: 29px;
                    text: I18n.text("elevator_calling");
                    color: #ffffffff;
                    font-family: "Inter";
                    font-size: 24px;
                    font-weight: 500;
                    horizontal-alignment: center;
                }
            }
            Rectangle {
                x: 890px; y: 0px;
                width: 110px;
                height: 420px;
                background: #00000000;
                Rectangle {
                    x: 0px; y: 0px;
                    width: 110px;
                    height: 252px;
                    background: @linear-gradient(225.000deg, #4f39f6ff 0%, #9810faff 100%);
                    border-radius: 16px;
                    Rectangle {
                        x: 42.887px; y: 116px;
                        width: 24.227px;
                        height: 20px;
                        background: #00000000;
                        Text {
                            width: parent.width;
                            height: parent.height;
                            text: I18n.text("request");
                            color: #ffffffff;
                            font-family: "Inter";
                            font-size: 14px;
                            font-weight: 500;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                        }
                    }
                    TouchArea { enabled: !State.ev-call-effect-active; width: parent.width; height: parent.height; clicked => { State.play-touch-sound(); State.ev-call-effect-active = true; } }
                }
                Rectangle {
                    x: 0px; y: 264px;
                    width: 110px;
                    height: 156px;
                    background: @linear-gradient(225.000deg, #314158ff 0%, #1d293dff 100%);
                    border-radius: 16px;
                    Image {
                        x: 39px; y: 48px;
                        width: 32px;
                        height: 32px;
                        source: @image-url("../assets/images/IugYF.png");
                        image-fit: contain;
                    }
                    Rectangle {
                        x: 42.887px; y: 88px;
                        width: 24.227px;
                        height: 20px;
                        background: #00000000;
                        Text {
                            width: parent.width;
                            height: parent.height;
                            text: I18n.text("cancel");
                            color: #ff0505ff;
                            font-family: "Inter";
                            font-size: 14px;
                            font-weight: 500;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                        }
                    }
                    TouchArea { enabled: !State.ev-cancel-effect-active; width: parent.width; height: parent.height; clicked => { State.play-touch-sound(); State.current-page = "LCvek"; State.pressed-effect = ""; State.call-effect-locked = false; State.ev-call-effect-active = false; State.ev-cancel-effect-active = false; } }
                }
            }
        }
        Rectangle {
            x: 0px; y: 470px;
            width: 1024px;
            height: 130px;
            background: #00000000;
            Rectangle {
                x: 24px; y: 43px;
                width: 976px;
                height: 44px;
                background: #1e293999;
                border-radius: 14px;
                Rectangle {
                    x: 24px; y: 12px;
                    width: 422.5px;
                    height: 20px;
                    background: #00000000;
                    Image {
                        x: 0px; y: 0px;
                        width: 20px;
                        height: 20px;
                        source: @image-url("../assets/images/EShJI.png");
                        image-fit: contain;
                    }
                    Rectangle {
                        x: 32px; y: 0px;
                        width: 72px;
                        height: 20px;
                        background: #00000000;
                        Text {
                            x: 0px; y: 0px;
                            width: 80px;
                            height: parent.height;
                            text: I18n.text("brightness");
                            color: #fafcff80;
                            font-family: "Inter";
                            font-size: 14px;
                            font-weight: 500;
                            vertical-alignment: center;
                        }
                    }
                    InteractiveSlider {
                        x: 112px; y: 0px;
                        width: 266.5px;
                        height: 20px;
                        track-y: 6px;
                        track-height: 8px;
                        setting-key: "call.ev.brightness";
                        value <=> State.ev-brightness-value;
                    }
                }
                Rectangle {
                    x: 529.5px; y: 12px;
                    width: 422.5px;
                    height: 20px;
                    background: #00000000;
                    Image {
                        x: 0px; y: 0px;
                        width: 20px;
                        height: 20px;
                        source: @image-url("../assets/images/ZbCsI.png");
                        image-fit: contain;
                        opacity: 0.5000;
                    }
                    Rectangle {
                        x: 32px; y: 0px;
                        width: 72px;
                        height: 20px;
                        background: #00000000;
                        opacity: 0.5000;
                        Text {
                            x: 0px; y: 0px;
                            width: parent.width;
                            height: parent.height;
                            text: I18n.text("volume");
                            color: #ffffffff;
                            font-family: "Inter";
                            font-size: 14px;
                            font-weight: 500;
                            vertical-alignment: center;
                        }
                    }
                    InteractiveSlider {
                        x: 112px; y: 0px;
                        width: 310.5px;
                        height: 20px;
                        track-y: 6px;
                        track-height: 8px;
                        setting-key: "call.ev.volume";
                        value <=> State.ev-volume-value;
                    }
                }
            }
        }
        Rectangle {
            x: 0px; y: 600px;
            width: 2731px;
            height: 4096px;
            background: #00000000;
            clip: true;
        }
    }
    if State.ev-call-effect-active: ButtonEffectLkIXT { x: 890px; y: 50px; }
    if State.ev-cancel-effect-active: ButtonEffectM9yPz { x: 890px; y: 314px; }
}
