import { State, I18n } from "shared.slint";

export component PasswordChange inherits Rectangle {
    private property <bool> can-submit: State.old-password-length == 6 && State.new-password-length == 6;

    width: 1024px;
    height: 600px;
    clip: true;
    background: #ffffffff;
    Rectangle {
        x: 0px; y: 0px;
        width: 1024px;
        height: 600px;
        background: #ffffffff;
        Rectangle {
            x: 0px; y: 0px;
            width: 1024px;
            height: 600px;
            background: @linear-gradient(210.368deg, #101828ff 0%, #1e2939ff 50%, #101828ff 100%);
            Rectangle {
                x: 60px; y: 24px;
                width: 904px;
                height: 48px;
                background: #00000000;
                Rectangle {
                    x: 24px; y: 0px;
                    width: 48px;
                    height: 48px;
                    background: #00000000;
                    border-radius: 16777200px;
                    Image {
                        x: 8px; y: 8px;
                        width: 32px;
                        height: 32px;
                        source: @image-url("../assets/images/1ZUDW.png");
                        image-fit: contain;
                    }
                    TouchArea { width: parent.width; height: parent.height; clicked => { State.play-touch-sound(); State.old-password = ""; State.old-password-length = 0; State.old-password-mask = ""; State.old-password-visible = false; State.new-password = ""; State.new-password-length = 0; State.new-password-mask = ""; State.password-visible = false; State.keyboard-target = ""; State.current-page = "gzCRD"; } }
                }
                Rectangle {
                    x: 366.477px; y: 0px;
                    width: 171.055px;
                    height: 48px;
                    background: #00000000;
                    Text {
                        x: 0px; y: -0.5px;
                        text: I18n.text("password_change");
                        color: #ffffffff;
                        font-family: "Inter";
                        font-size: 32px;
                        font-weight: 500;
                    }
                }
            }
            Rectangle {
                x: 262px; y: 96px;
                width: 500px;
                height: 480px;
                background: #00000000;
                Rectangle {
                    x: 0px; y: 85.75px;
                    width: 500px;
                    height: 94px;
                    background: #00000000;
                    Rectangle {
                        x: 0px; y: 0px;
                        width: 500px;
                        height: 24px;
                        background: #00000000;
                        Text {
                            width: parent.width;
                            height: parent.height;
                            text: I18n.text("current_password");
                            color: #ffffffff;
                            font-family: "Inter";
                            font-size: 16px;
                            font-weight: 500;
                            vertical-alignment: center;
                        }
                    }
                    Rectangle {
                        x: 0px; y: 36px;
                        width: 500px;
                        height: 58px;
                        background: #00000000;
                        Rectangle {
                            x: 0px; y: 0px;
                            width: 500px;
                            height: 58px;
                            background: #ffffff0d;
                            border-radius: 14px;
                            border-color: #ffffff1a;
                            border-width: 1px;
                            Image {
                                x: 20px; y: 19px;
                                width: 20px;
                                height: 20px;
                                source: @image-url("../assets/images/3nodO.png");
                                image-fit: contain;
                            }
                            Rectangle {
                                x: 52px; y: 17px;
                                width: 340px;
                                height: 24px;
                                background: #00000000;
                                Text {
                                    width: parent.width;
                                    height: parent.height;
                                    text: State.old-password == "" ? I18n.text("enter_password_placeholder") : (State.old-password-visible ? State.old-password : State.old-password-mask);
                                    color: #ffffffff;
                                    font-family: "Inter";
                                    font-size: 16px;
                                    font-weight: 500;
                                    vertical-alignment: center;
                                }
                            }
                            Rectangle {
                                x: 400px; y: 19.25px;
                                width: 44px;
                                height: 19.5px;
                                background: #00000000;
                                Text {
                                    width: parent.width;
                                    height: parent.height;
                                    text: I18n.char_count_label(State.old-password-length);
                                    color: #ffffff66;
                                    font-family: "Inter";
                                    font-size: 13px;
                                    font-weight: 500;
                                    horizontal-alignment: right;
                                    vertical-alignment: center;
                                }
                            }
                            Rectangle {
                                x: 0px; y: 0px;
                                width: 444px;
                                height: 58px;
                                background: #00000000;
                                TouchArea {
                                    width: parent.width;
                                    height: parent.height;
                                    clicked => { State.play-touch-sound(); State.old-password-visible = false; State.keyboard-target = "old-password"; State.active-overlay = "Q7BQ4"; }
                                }
                            }
                        }
                        Rectangle {
                            x: 452px; y: 11px;
                            width: 36px;
                            height: 36px;
                            background: #00000000;
                            border-radius: 8px;
                            Image {
                                x: 8px; y: 8px;
                                width: 20px;
                                height: 20px;
                                source: State.old-password-visible ? @image-url("../assets/images/B95EY.png") : @image-url("../assets/images/XYnkN.png");
                                image-fit: contain;
                            }
                            TouchArea {
                                width: parent.width;
                                height: parent.height;
                                clicked => { State.play-touch-sound(); State.old-password-visible = !State.old-password-visible; }
                            }
                        }
                    }
                }
                Rectangle {
                    x: 0px; y: 203.75px;
                    width: 500px;
                    height: 94px;
                    background: #00000000;
                    Rectangle {
                        x: 0px; y: 0px;
                        width: 500px;
                        height: 24px;
                        background: #00000000;
                        Text {
                            width: parent.width;
                            height: parent.height;
                            text: I18n.text("new_password");
                            color: #ffffffff;
                            font-family: "Inter";
                            font-size: 16px;
                            font-weight: 500;
                            vertical-alignment: center;
                        }
                    }
                    Rectangle {
                        x: 0px; y: 36px;
                        width: 500px;
                        height: 58px;
                        background: #ffffff0d;
                        border-radius: 14px;
                        border-color: #ffffff1a;
                        border-width: 1px;
                        Image {
                            x: 20px; y: 19px;
                            width: 20px;
                            height: 20px;
                            source: @image-url("../assets/images/3nodO.png");
                            image-fit: contain;
                        }
                        Rectangle {
                            x: 52px; y: 17px;
                            width: 340px;
                            height: 24px;
                            background: #00000000;
                            Text {
                                width: parent.width;
                                height: parent.height;
                                text: State.new-password == "" ? I18n.text("enter_password_placeholder") : (State.password-visible ? State.new-password : State.new-password-mask);
                                color: #ffffffff;
                                font-family: "Inter";
                                font-size: 16px;
                                font-weight: 500;
                                vertical-alignment: center;
                            }
                        }
                        Rectangle {
                            x: 400px; y: 19.25px;
                            width: 44px;
                            height: 19.5px;
                            background: #00000000;
                            Text {
                                width: parent.width;
                                height: parent.height;
                                text: I18n.char_count_label(State.new-password-length);
                                color: #ffffff66;
                                font-family: "Inter";
                                font-size: 13px;
                                font-weight: 500;
                                horizontal-alignment: right;
                                vertical-alignment: center;
                            }
                        }
                        Rectangle {
                            x: 0px; y: 0px;
                            width: 444px;
                            height: 58px;
                            background: #00000000;
                            TouchArea {
                                width: parent.width;
                                height: parent.height;
                                clicked => { State.play-touch-sound(); State.password-visible = false; State.keyboard-target = "new-password"; State.active-overlay = "Siq8B"; }
                            }
                        }
                        Rectangle {
                            x: 452px; y: 11px;
                            width: 36px;
                            height: 36px;
                            background: #00000000;
                            border-radius: 8px;
                            Image {
                                x: 9px; y: 9px;
                                width: 18px;
                                height: 18px;
                                source: State.password-visible ? @image-url("../assets/images/B95EY.png") : @image-url("../assets/images/XYnkN.png");
                                image-fit: contain;
                            }
                            TouchArea {
                                width: parent.width;
                                height: parent.height;
                                clicked => { State.play-touch-sound(); State.password-visible = !State.password-visible; }
                            }
                        }
                    }
                }
                    Rectangle {
                        x: 0px; y: 337.75px;
                        width: 500px;
                        height: 56.5px;
                        background: root.can-submit ? #155dfcff : #ffffff0d;
                        border-radius: 14px;
                        Text {
                            width: parent.width;
                            height: parent.height;
                            text: I18n.text("password_change");
                            color: root.can-submit ? #ffffffff : #ffffff4d;
                            font-family: "Inter";
                            font-size: 16px;
                            font-weight: 500;
                            horizontal-alignment: center;
                            vertical-alignment: center;
                        }
                        TouchArea {
                            width: parent.width;
                            height: parent.height;
                            clicked => {
                                if root.can-submit {
                                    State.play-touch-sound();
                                    State.change-password(State.old-password, State.new-password);
                                }
                            }
                        }
                    }
                }
            }
    }
}
